import { createFileRoute } from "@tanstack/react-router";
import { AppShell } from "@/components/layout/AppShell";
import { useReports, useReportsSummary } from "@/hooks";
import { StatCard } from "@/components/cards/StatCard";
import { FileText, CalendarClock, FilePlus, HardDrive, Download } from "lucide-react";
import { Button } from "@/components/ui/button";
import { useState } from "react";

export const Route = createFileRoute("/_app/reports")({ component: ReportsPage });

function ReportsPage() {
  const [page, setPage] = useState(1);
  const { data: summary } = useReportsSummary();
  const { data } = useReports({ page, pageSize: 10 });

  return (
    <AppShell title="Reports" subtitle="Generate and download system reports">
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
        <StatCard icon={FileText} label="Total Reports" value={summary?.total ?? 0} hint="Generated" tone="info" />
        <StatCard icon={CalendarClock} label="Scheduled" value={summary?.scheduled ?? 0} hint="Automated" tone="success" />
        <StatCard icon={FilePlus} label="Manual Reports" value={summary?.manual ?? 0} hint="Generated" tone="warning" />
        <StatCard icon={HardDrive} label="Data Exported" value={`${summary?.exportedGb ?? 0} GB`} hint="This Period" tone="default" />
      </div>

      <div className="glass-card rounded-xl p-5">
        <div className="overflow-x-auto">
          <table className="w-full text-sm">
            <thead className="text-xs text-muted-foreground border-b border-border">
              <tr className="text-left">
                <th className="py-3 px-2">Report Name</th><th>Type</th><th>Date Range</th><th>Generated On</th><th>Generated By</th><th>Format</th><th>Size</th><th>Actions</th>
              </tr>
            </thead>
            <tbody>
              {data?.data.map((r) => (
                <tr key={r.id} className="border-b border-border/50 hover:bg-accent/30">
                  <td className="py-3 px-2 font-medium">{r.name}</td>
                  <td className="text-muted-foreground">{r.type}</td>
                  <td className="text-muted-foreground">{r.dateRange}</td>
                  <td>{r.generatedOn}</td>
                  <td className="text-muted-foreground">{r.generatedBy}</td>
                  <td><span className="px-2 py-0.5 rounded bg-primary/15 text-primary text-xs font-medium">{r.format}</span></td>
                  <td>{r.sizeMb} MB</td>
                  <td><Button variant="ghost" size="icon"><Download className="size-4" /></Button></td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
        <div className="flex items-center justify-between mt-4">
          <div className="text-xs text-muted-foreground">Showing {data ? (page - 1) * 10 + 1 : 0} to {Math.min(page * 10, data?.total ?? 0)} of {data?.total ?? 0}</div>
          <div className="flex gap-1">
            {Array.from({ length: Math.min(5, Math.ceil((data?.total ?? 0) / 10)) }).map((_, i) => (
              <Button key={i} variant={page === i + 1 ? "default" : "outline"} size="sm" onClick={() => setPage(i + 1)}>{i + 1}</Button>
            ))}
          </div>
        </div>
      </div>
    </AppShell>
  );
}
